version: 2.1
general:
  branches:
    only:
      - master
# orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  # localstack: localstack/platform@1.0.0
  # python: circleci/python@1.2
workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-docker:
          context:
            - secrets


jobs:
  build-docker:
    working_directory: /app
    docker:
      - image: docker:20.10.9-git
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apk add --no-cache \
      #         py-pip=9.0.0-r1
      #       pip install \
      #         docker-compose==1.12.0 \
      #         awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              docker tag app "lewelyn/cryptoparadise-jupyter:${CIRCLE_SHA1}"
              docker tag app "lewelyn/cryptoparadise-jupyter:latest"
              docker push lewelyn/cryptoparadise-jupyter --all-tags
            fi
