# example of bot_entity configuration

# start_balance: 10000
# min_balance: 100
transaction_amount: 50
stop_loss: 20

exchange: binance
currency_pairs:
  - ETH/EUR
  - DOT/USDT
timeframe: 1m
last_n_candles: 200
# roi_stop: 10
sell_all: False
timeout: 300000
max_open_trades: 15
#start_time: '2019-06-01 12:22:00'